WIP : Mmaintenance window resource
russellcardullo/terraform-provider-pingdom pull request #63
Opened 2020-04-09 09:56 UTC by nlamirault

Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

2020-05-28 13:03 UTC, dchancogne commented
Any chance this can be merged soon-ish? Thank you.

2020-06-13 19:43 UTC, dchancogne commented
Please, pretty please!

2020-07-06 19:12 UTC, dchancogne commented
Looks like there has been activity. What remains to be done for this to be merged? Anything I can do that would be useful?

2020-09-13 18:10 UTC, russellcardullo requested changes
I get some errors when trying to use this.  Would you mind fixing those as well as updating the README with some documentation on the new resource?

2020-09-13 18:10 UTC, russellcardullo commented on pingdom/resource_pingdom_maintenance_window.go
> +	"github.com/hashicorp/terraform/helper/schema"
Can you change this to use github.com/hashicorp/terraform-plugin-sdk/helper/schema?

2020-09-13 18:10 UTC, russellcardullo commented on pingdom/resource_pingdom_maintenance_window.go
> +		windowParams.To = v.(int64)
I get a panic on this line: `panic: interface conversion: interface {} is int, not int64`.  I think this and the `from` param should probably be changed to `int` as the terraform SDK only has `TypeInt`.

2021-04-20 08:15 UTC, nlamirault commented
My bad @russellcardullo @dchancogne I didn't have time to work on it at all. Prefer #98

2021-04-20 08:15 UTC, closed without merging